import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Icons } from "@/components/Icons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chris Digital | Fullstack E-Commerce Marketplace",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-cdm.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative h-full`}
      >
        <main className="relative flex flex-col min-h-screen">
          <Navbar/>
          <div className="flex-grow flex-1">{children}</div>
        </main>
        
      </body>
    </html>
  );
}
